### PR TITLE
Added article on ListView filtering

### PR DESCRIPTION
**Pull request by bekwam**

### CODE REVIEW

**Comment by JonathanGiles** [comment]
We need to come up with a good structure for the document. I see you've created a new asciidoc file, and it is not included in the index.asc. This means that the document will not be available in the main index.html or book.pdf files that are created.

What are your thoughts about putting this into the existing ui-controls asciidoc section, perhaps with a section specifically with a header for ListView?

**Comment by bekwam** [comment]
I think it controls is perfect.  Feel free to categorize my submissions anyway you see fit.

**Comment by JonathanGiles** [comment]
In that case I'll merge your changes, and then move them into their 'rightful' home. Thanks so much for your contribution! I plan to do a big push on this over the next few months, and I really appreciate your support. As I said on Twitter, we really should mine your blog for the most useful information and get it all captured inside a single 'book'.

**Comment by JonathanGiles** [comment]
Merged and moved into better location: https://fxdocs.github.io/docs/index.html#_listview

**Pull request merged**
